hl_password_policies:
  password_policies:
    default:
      minimumLength: 8
      options:
        digitCharacterRequired: 1
        lowerCaseCharacterRequired: 1
        upperCaseCharacterRequired: 1
        specialCharacterRequired: 1
      charakterVariance: 3

    admin:
      minimumLength: 16
      options:
        digitCharacterRequired: 1
        lowerCaseCharacterRequired: 1
        upperCaseCharacterRequired: 1
        specialCharacterRequired: 1
      charakterVariance: 4
