hl_password_policies:
  password_policies:
    default:
      minimumLength: 8
      checkCharacters:
        digitCharacter: 1
        lowerCaseCharacter: 1
        upperCaseCharacter: 1
        specialCharacter: 1
      charakterVariance: 3
    admin:
      minimumLength: 4
      checkCharacters:
        digitCharacter: 1
        lowerCaseCharacter: 1
        upperCaseCharacter: 1
        specialCharacter: 1
      charakterVariance: 4